### ISSUE TITLE
zip download does not include the drivers

### ISSUE THREAD

**Issue by bdlabitt** [lvgl/lv_port_pc_eclipse#113]
Existing zip file does not include the contents of lvgl or lv_drivers directories.  If you are going to offer a zip, it would be good if the download was complete.  Otherwise, there's not much point to it.

My workaround is to use git.  I hadn't wanted to bother, but apparently this is currently necessary.

**Comment by embeddedt** [comment]
See https://github.com/lvgl/lv_port_win_visual_studio/issues/33#issuecomment-905443065. Nothing we can do about this as it's a GitHub issue.
