### ISSUE TITLE
MOUSE is not work on submodule lv_drivers v8.3.0  

### ISSUE THREAD

**Issue by kay54068** [lvgl/lv_port_pc_eclipse#114]
i want use the  lv_port_pc_eclipse project.

the demo is work fine on 8.3.0 dev(1bd4368e) , but i get some problems when i update to  lv_drivers to v8.3.0 (462d9cde):

![image](https://user-images.githubusercontent.com/3054544/196912064-ba95adb9-45c8-4606-b649-d3cf594cf720.png)

i check is the lv_driver repo ,  the  issue is happened after 462d9cde.

btw,
the current  lv_drv_conf.h USE_SDL setting seems a bit strange:
![image](https://user-images.githubusercontent.com/3054544/196914142-445b2b9d-7979-4f91-98a1-479b96653b2d.png)

**Comment by kisvegabor** [comment]
I've updated both the `release/v8` and the `master` branch. All should work now.

**Comment by kay54068** [comment]
@kisvegabor  
it's work for me.  thanks.

**Comment by kisvegabor** [comment]
Great! :slightly_smiling_face:
