### ISSUE TITLE
Cmake build error

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_pc_eclipse#141]
A friend of mine just reported the issue of having these CMake build errors:
```
  Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES)
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
```

@XuNeo Could you take look at it?

**Comment by kisvegabor** [comment]
Thank you for the quick reply. I asked m fried to join the discussion in order to better understand the issue.

**Comment by ygramoel** [comment]
I reported this.

I ran into this issue while following the instructions on  https://github.com/lvgl/lv_port_pc_eclipse on my Linux desktop running Mint 20.3.  

This is what I did (leaving out most of the command output):
```
$ git clone --recursive https://github.com/littlevgl/pc_simulator_sdl_eclipse.git
...
$ sudo apt install libsdl2-dev
...
$ cmake .. -DLV_USE_DRAW_SDL=ON -DLV_USE_LIBPNG=ON -DLV_USE_LIBJPEG_TURBO=ON
...
Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES)
...
$ sudo apt install libsdl2-image-dev
...
$ cmake .. -DLV_USE_DRAW_SDL=ON -DLV_USE_LIBPNG=ON -DLV_USE_LIBJPEG_TURBO=ON
...
Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
...
$ sudo apt install libjpeg-dev
...
$ cmake .. -DLV_USE_DRAW_SDL=ON -DLV_USE_LIBPNG=ON -DLV_USE_LIBJPEG_TURBO=ON
...
(normal termination - cmake worked)
```


First, I got this error while running cmake:
`Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES)`

I fixed that by executing this command:
