### ISSUE TITLE
lv_port_pc_eclipse V9 build failure[windows]

### ISSUE THREAD

**Issue by 19e2k67** [lvgl/lv_port_pc_eclipse#149]
![Snipaste_2024-02-02_16-07-01](https://github.com/lvgl/lv_port_pc_eclipse/assets/102461738/9320cb7e-854f-467d-a43f-e39249b4d3e3)
```
function 'Tvg_Result tvg_engine_init(Tvg_Engine, unsigned int)' definition is marked dllimportGCC
'Tvg_Result tvg_engine_init(Tvg_Engine, unsigned int)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]GCC
Tvg_Result tvg_engine_init(Tvg_Engine engine_method, unsigned int threads)
Engine API
Initializes TVG engines. TVG requires the running-engine environment. TVG runs its own task-scheduler for parallelizing rendering tasks efficiently. You can indicate the number of threads, the count of which is designated threads. In the initialization step, TVG will generate/spawn the threads as set by threads count. tvg_engine_init(TVG_ENGINE_SW, 0); //Initialize software renderer and use the main thread only

Parameters:
engine_method – The engine types to initialize. This is relative to the Canvas types, in which it will be used. For multiple backends bitwise operation is allowed. - TVG_ENGINE_SW: CPU rasterizer - TVG_ENGINE_GL: OpenGL rasterizer (not supported yet)
threads – The number of additional threads used to perform rendering. Zero indicates only the main thread is to be used.

Returns:
Tvg_Result enumeration.

Return values:
TVG_RESULT_SUCCESS Succeed.
TVG_RESULT_FAILED_ALLOCATION An internal error possibly with memory allocation.
TVG_RESULT_INVALID_ARGUMENT Unknown engine type.
TVG_RESULT_NOT_SUPPORTED Unsupported engine type.
TVG_RESULT_UNKNOWN Other error.

Note:
The Initializer keeps track of the number of times it was called. Threads count is fixed at the first init() call.
```
I am using the version in the folder，
![Snipaste_2024-02-02_15-54-16](https://github.com/lvgl/lv_port_pc_eclipse/assets/102461738/ac2b10b8-bf45-414b-bf77-84de3a3b0f45)
Low version (requires lv_drivers folder) can successfully build
![Snipaste_2024-02-02_16-11-42](https://github.com/lvgl/lv_port_pc_eclipse/assets/102461738/ff06ace9-6b22-4fb4-ac01-c23488f55b30)
Please tell me what I should do?

**Comment by wxlinus** [comment]
I also encountered this problem
![image](https://github.com/lvgl/lv_port_pc_eclipse/assets/32796193/e7ccdd45-df50-47b0-8f0f-eb278d48d8fc)

**Comment by kisvegabor** [comment]
Does it help if you add `#define TVG_BUILD 1` [here](https://github.com/lvgl/lvgl/blob/master/src/libs/thorvg/thorvg.h#L29)?

**Comment by 19e2k67** [comment]
![Snipaste_2024-02-05_19-32-51](https://github.com/lvgl/lv_port_pc_eclipse/assets/102461738/67316fd1-b376-4542-89ee-8171c1f770bf)

**Comment by wxlinus** [comment]
I solved this problem by changing mingw64 to cygwin, and then I compiled and installed SDL2, but I couldn't use debug because gcc under win is missing ASAN related libraries

**Comment by wxlinus** [comment]
![Uploading image.png…]()


> I solved this problem by changing mingw64 to cygwin, and then I compiled and installed SDL2, but I couldn't use debug because gcc under win is missing ASAN related libraries

**Comment by kisvegabor** [comment]
Feel free to disable ASAN. It's just optional.

**Comment by wxlinus** [comment]
Thank you！

**Comment by wendaoyifei** [comment]
I had the same problem, what's the meaning of changing mingw64 to cygwin @wxlinus .   I worded in windows platform and use mingw and vscode， I am not get used to use codeblock even thoug it's recommended in windows platfrom

**Comment by 19e2k67** [comment]
Should we ask questions in this [project](https://github.com/lvgl/lv_port_pc_vscode)?

**Comment by kisvegabor** [comment]
> Should we ask questions in this [project](https://github.com/lvgl/lv_port_pc_vscode)?

Oh yes, as it's VS code please open a new issue in https://github.com/lvgl/lv_port_pc_vscode

**Comment by yaoxuexill** [comment]
![6592fdd99848cbd0e7b216c096996e7](https://github.com/user-attachments/assets/3ed4784d-c5d8-4441-9758-f03ec4eb1e69)
Adding a sentence with a red line may solve your problem
