### ISSUE TITLE
lvgl master 2024.3.4 lvgl::thorvg compile error

### ISSUE THREAD

**Issue by rx-ted** [lvgl/lv_port_pc_eclipse#150]
2024.3.4
git pull to download the least branch of lvgl master, but `lvgl::thorvg` compiled error, see:
```bash
Target "main" links to target "lvgl::thorvg" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by kisvegabor** [comment]
How do you build the project?

**Comment by rx-ted** [comment]
Sorry, I have resolved it. The reason is that the dependency file cannot be found.

**Comment by kisvegabor** [comment]
> Sorry, I have resolved it. The reason is that the dependency file cannot be found.

To help others, could you elaborate on this?

**Comment by Atul-8** [comment]
I will lv_drivers and lvgl clone in this project according to a tutorial. When I compile, I will be prompted that SDL2 this file cannot be found.

**Comment by Atul-8** [comment]
> > Sorry, I have resolved it. The reason is that the dependency file cannot be found.
> 
> To help others, could you elaborate on this?

I will lv_drivers and lvgl clone in this project according to a tutorial. When I compile, I will be prompted that SDL2 this file cannot be found.

**Comment by rx-ted** [comment]
> > > Sorry, I have resolved it. The reason is that the dependency file cannot be found.
> > 
> > 
> > To help others, could you elaborate on this?
> 
> I will lv_drivers and lvgl clone in this project according to a tutorial. When I compile, I will be prompted that SDL2 this file cannot be found.

Yeah, that is the same with yours.

**Comment by rx-ted** [comment]
My solution is as follows:
Root directory: CMakeLists.txt:29
```makefile
target_link_libraries(main lvgl lvgl::examples lvgl::demos lvgl::thorvg ${SDL2_LIBRARIES} m pthread)
```
Remove `lvgl::thorvg`, change to
```makefile
target_link_libraries(main lvgl lvgl::examples lvgl::demos ${SDL2_LIBRARIES} m pthread)
```
This is my idea. I really can't think of anything else.
If you has great idea, pls tell me. TKS.

**Comment by kisvegabor** [comment]
Does it fail for you with clean clone and build too? I've just tested with:
```
mkdir build
cd build
cmake ..
make -j
```

and it worked well.
