### ISSUE TITLE
lv_obj_get_ API can't working properly

### ISSUE THREAD

**Issue by Cun-Jiang** [lvgl/lv_port_pc_eclipse#153]
I use a label to display the width of object, for example:
`lv_obj_t *label=lv_label_create(lv_screen_active());
lv_label_set_text_fmt(label,"debug: %d",lv_obj_get_width(label));`
 but I find it always returns 0.
The following APIs have the same result:
`lv_obj_get_x();lv_obj_get_y();lv_obj_get_height()...`

**Comment by kisvegabor** [comment]
Hi,

Take a look at this: https://docs.lvgl.io/master/overview/coord.html#postponed-coordinate-calculation

**Comment by Cun-Jiang** [comment]
Thank you!
