### ISSUE TITLE
x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan: No such file or directory  ，cannot find -lubsan: No such file or directory

### ISSUE THREAD

**Issue by dancemanUK** [lvgl/lv_port_pc_eclipse#154]
[build] [ 98%] Linking C static library ..\lib\liblvgl_examples.a
[build] [ 99%] Built target lvgl_examples
[build] [ 99%] Building C object CMakeFiles/main.dir/main.c.obj
[build] [ 99%] Building C object CMakeFiles/main.dir/mouse_cursor_icon.c.obj
[build] [100%] Linking CXX executable G:\soc\lvgl\v9.2\lv_port_pc_eclipse\bin\main.exe
[build] D:/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan: No such file or directory
[build] D:/tools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lubsan: No such file or directory
[build] collect2.exe: error: ld returned 1 exit status
[build] mingw32-make[2]: *** [CMakeFiles\main.dir\build.make:123: G:/soc/lvgl/v9.2/lv_port_pc_eclipse/bin/main.exe] Error 1
[build] mingw32-make[1]: *** [CMakeFiles\Makefile2:109: CMakeFiles/main.dir/all] Error 2
[build] mingw32-make: *** [Makefile:135: all] Error 2
[proc] 命令“D:\tools\CMake\bin\cmake.EXE --build g:/soc/lvgl/v9.2/lv_port_pc_eclipse/build --config Debug --target all -j 34 --”已退出，代码为 2
[driver] 生成完毕: 00:00:58.413

Thread model: win32
Supported LTO compression algorithms: zlib
gcc version 13.2.0 (x86_64-win32-seh-rev1, Built by MinGW-Builds project) 

in v9.2\lv_port_pc_eclipse

<img width="1419" alt="wechat_20240913214822" src="https://github.com/user-attachments/assets/158596ec-5c89-4427-91a3-e7aa30631762">

**Comment by kisvegabor** [comment]
It happens because MinGW doesn't support ASAN.

For VSCode I suggest using [this repo](https://github.com/lvgl/lv_port_pc_vscode/) where ASAN is already disabled by default.

**Comment by dancemanUK** [comment]
> 发生这种情况是因为 MinGW 不支持 ASAN。
> 
> 对于 VSCode，我建议使用[这个 repo](https://github.com/lvgl/lv_port_pc_vscode/)，其中 ASAN 默认已禁用。



> It happens because MinGW doesn't support ASAN.
> 
> For VSCode I suggest using [this repo](https://github.com/lvgl/lv_port_pc_vscode/) where ASAN is already disabled by default.

Thankyou!

**Comment by kisvegabor** [comment]
It seems it answers your question, so I close this issue.

**Comment by FGQ1001** [comment]
要解决这个err需要修改两个地方：
1、屏蔽CMakeLits.txt文件中    
    target_compile_options(main PRIVATE -fsanitize=address,leak,undefined)
    target_link_options(main PRIVATE -fsanitize=address,leak,undefined)
这两句；
2、在main.c文件中添加#include <SDL2/SDL.h>声明。
解决！！
