### ISSUE TITLE
PC Simulator v5.2 Build Error

### ISSUE THREAD

**Issue by broberto** [lvgl/lv_port_pc_eclipse#31]
Eclipse reported an error during a PC Simulator build (see below).

PC-Simulator v5.2
System: HP ZBook 15u G3
System Type: x64-based PC
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.17134 Build 17134
Build Env:	msys64 / gcc (GCC) 7.3.0

Eclipse IDE for C/C++ Developers
Version: 2018-09 (4.9.0)
Build id: 20180917-1800

# build errors 
Description |   Resource |      Path |  Location |      Type
'_beginthreadex' undeclared (first use in this function) |      monitor.c |     /pc_simulator/lv_drivers/display |      line 88 |       C/C++ Problem
'_endthreadex' undeclared (first use in this function); did you mean '_beginthreadex'? |        monitor.c |     /pc_simulator/lv_drivers/display |      line 88 |       C/C++ Problem

# full console log
08:52:08 **** Incremental Build of configuration Debug for project pc_simulator ****
Info: Internal Builder is used for build
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_drivers\\indev\\keyboard.o" "..\\lv_drivers\\indev\\keyboard.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_fonts\\lv_font_dejavu_30.o" "..\\lvgl\\lv_fonts\\lv_font_dejavu_30.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_apps\\demo\\demo.o" "..\\lv_examples\\lv_apps\\demo\\demo.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_drivers\\indev\\evdev.o" "..\\lv_drivers\\indev\\evdev.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tutorial\\4_themes\\lv_tutorial_themes.o" "..\\lv_examples\\lv_tutorial\\4_themes\\lv_tutorial_themes.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_fonts\\lv_font_builtin.o" "..\\lvgl\\lv_fonts\\lv_font_builtin.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tests\\lv_test_theme\\lv_test_theme.o" "..\\lv_examples\\lv_tests\\lv_test_theme\\lv_test_theme.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_apps\\benchmark\\benchmark_bg.o" "..\\lv_examples\\lv_apps\\benchmark\\benchmark_bg.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tests\\lv_test_objx\\lv_test_gauge\\lv_test_gauge.o" "..\\lv_examples\\lv_tests\\lv_test_objx\\lv_test_gauge\\lv_test_gauge.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tutorial\\0_porting\\lv_tutorial_porting.o" "..\\lv_examples\\lv_tutorial\\0_porting\\lv_tutorial_porting.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_objx\\lv_line.o" "..\\lvgl\\lv_objx\\lv_line.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tests\\lv_test_objx\\lv_test_imgbtn\\imgbtn_img_2.o" "..\\lv_examples\\lv_tests\\lv_test_objx\\lv_test_imgbtn\\imgbtn_img_2.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_core\\lv_group.o" "..\\lvgl\\lv_core\\lv_group.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_objx\\lv_ddlist.o" "..\\lvgl\\lv_objx\\lv_ddlist.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tutorial\\6_images\\red_flower.o" "..\\lv_examples\\lv_tutorial\\6_images\\red_flower.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tutorial\\5_antialiasing\\apple_icon_alpha.o" "..\\lv_examples\\lv_tutorial\\5_antialiasing\\apple_icon_alpha.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_objx\\lv_img.o" "..\\lvgl\\lv_objx\\lv_img.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_examples\\lv_tests\\lv_test_objx\\lv_test_page\\lv_test_page.o" "..\\lv_examples\\lv_tests\\lv_test_objx\\lv_test_page\\lv_test_page.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_objx\\lv_tabview.o" "..\\lvgl\\lv_objx\\lv_tabview.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_themes\\lv_theme_nemo.o" "..\\lvgl\\lv_themes\\lv_theme_nemo.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_drivers\\display\\fbdev.o" "..\\lv_drivers\\display\\fbdev.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lvgl\\lv_objx\\lv_btnm.o" "..\\lvgl\\lv_objx\\lv_btnm.c"
gcc "-IC:\\sandbox\\pc-simulator\\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -o "lv_drivers\\display\\monitor.o" "..\\lv_drivers\\display\\monitor.c"
In file included from /usr/include/SDL2/SDL_audio.h:35:0,
                 from /usr/include/SDL2/SDL.h:36,
                 from ..\lv_drivers\display\monitor.c:19:
..\lv_drivers\display\monitor.c: In function 'monitor_init':
..\lv_drivers\display\monitor.c:88:5: error: '_beginthreadex' undeclared (first use in this function)
     SDL_CreateThread(monitor_sdl_refr_thread, "sdl_refr", NULL);
     ^
..\lv_drivers\display\monitor.c:88:5: note: each undeclared identifier is reported only once for each function it appears in
..\lv_drivers\display\monitor.c:88:5: error: '_endthreadex' undeclared (first use in this function); did you mean '_beginthreadex'?
     SDL_CreateThread(monitor_sdl_refr_thread, "sdl_refr", NULL);
     ^

08:52:44 Build Failed. 2 errors, 0 warnings. (took 36s.29ms)

**Comment by broberto** [comment]
I changed the Eclipse setting from Internal CDT Builder to GNU Make Builder and got a different error:

Building file: ../lv_drivers/display/monitor.c
Invoking: GCC C Compiler
gcc -I"C:\sandbox\pc-simulator\pc_simulator" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"lv_drivers/display/monitor.d" -MT"lv_drivers/display/monitor.o" -o "lv_drivers/display/monitor.o" "../lv_drivers/display/monitor.c"
In file included from ../lv_drivers/display/monitor.h:19,
                 from ../lv_drivers/display/monitor.c:9:
../lv_drivers/display/../../lv_drv_conf.h:89:37: fatal error: SDL2/SDL.h: No such file or directory
 #define MONITOR_SDL_INCLUDE_PATH    <SDL2/SDL.h>    /*Eclipse: <SDL2/SDL.h>    Visual Studio: <SDL.h>*/
                                     ^
compilation terminated.
make: *** [lv_drivers/display/subdir.mk:32: lv_drivers/display/monitor.o] Error 1

**Comment by embeddedt** [comment]
@broberto Looks like libsdl isn't in your include path.

**Comment by broberto** [comment]
Pls ignore my last msg.  As an experiment, I set my sys path to point to a mingw/bin dir instead of my usual msys2/usr/bin dir and forgot to reset it.

The error from my first post is what I'm working from.  

@embeddedt Is your observation based on my first or second post?

**Comment by kisvegabor** [comment]
Do you use mingw?

**Comment by kisvegabor** [comment]
I found this: https://discourse.libsdl.org/t/bug-in-thread-implementation-under-windows/12747/5
Maybe a missing DLL?

**Comment by kisvegabor** [comment]
Glad to hear you made it work!

**Comment by broberto** [comment]
@Jekyll555 If CodeBlocks doesn't work out post the error message from Eclipse.
The WIN/Eclipse example works out of the box.

**Comment by Jekyll555** [comment]
@broberto Thanks for getting back to me. 
I luckily had the out-of-the-box experience yesterday with my codeblocks installed and using the respective sample simulation. Thanks @embeddedt .
